apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-assignment-deployment
  labels:
    app: myApp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myApp
  template:
    metadata:
      labels:
        app: myApp
    spec:
      containers:
        - name: my-app-container
          image: amitgupta05/docker_kubernetes_assignment:1.0
          ports:
            - containerPort: 8085



